name: tests

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  poc_tests:
    runs-on: ubuntu-latest
    steps:
      - name: "check out main"
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: "install node"
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: "install dependencies"
        run: npm i

      - name: 'Install playwright browsers'
        run: npx playwright install

      - name: "Install Allure Commandline"
        run: npm install -g allure-commandline --save-dev 

      - name: 'Run poc tests'
        run: npx codeceptjs run --reporter mocha-multi

      - name: XUnit Viewer
        uses: AutoModality/action-xunit-viewer@v1.0.1
        with:
          results: ./output/result.xml

      - name: 'Install Java 11 (Required for Allure)'
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk

      - name: 'Generate Allure Report'
        run: npx allure generate allure-results --clean --output allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4.4.3
        with:
          name: poc-artifact
          path: |
            output
        if: always()
