name: tests

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  poc_tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out main"
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: "Install node"
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: "Install dependencies"
        run: npm i

      - name: "Install playwright browsers"
        run: npx playwright install

      - name: "Run poc tests"
        run: npx codeceptjs run --reporter mocha-multi

      - name: "XUnit Viewer"
        uses: AutoModality/action-xunit-viewer@v1.0.1
        with:
          results: ./output/result.xml

      - name: "Install Java 11 (Required for Allure)"
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk

      - name: "Load test reports history"
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh_pages
          path: gh_pages

      - name: "Build test report"
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh_pages
          allure_history: allure-history
          allure_results: allure-results

      - name: "Verify allure-history content"
        run: |
          echo "Contents of allure-history directory:"
          ls -al allure-history  # List files in the allure-history directory
          cat allure-history/index.html  # Display the contents of index.html (optional, for debugging)
        if: always()

      # Move the contents of allure-history to the root directory for proper serving
      - name: "Move Allure Report to Root"
        run: |
          mv allure-history/* .   # Move all files from allure-history to the root folder
          rm -rf allure-history   # Re
